site_name: Siddhi IO IBMMQ
site_description: Siddhi IO IBMMQ Extension
repo_name: Siddhi-IO-IBMMQ
repo_url: https://github.com/siddhi.io/siddhi-io-ibmmq
edit_uri: https://github.com/siddhi.io/siddhi-io-ibmmq/blob/master
copyright: Siddhi - Documentation
theme:
  name: material
  logo: images/siddhi-logo.svg
  favicon: images/favicon.ico
  palette:
    primary: teal
    accent: teal
extra_css:
  - assets/stylesheets/extra.css
extra_javascript:
  - assets/javascripts/extra.js
extra:
  social:
    - type: github
      link: https://github.com/siddhi-io/siddhi
    - type: medium
      link: https://medium.com/siddhi-io
    - type: twitter
      link: https://twitter.com/siddhi_io
    - type: linkedin
      link: https://www.linkedin.com/groups/13553064
google_analytics:
  - UA-103065-28
  - auto
markdown_extensions:
  - markdown.extensions.admonition
pages:
- Information: index.md
- API Docs:
  - 1.1.2: api/1.1.2.md
  - 1.1.1: api/1.1.1.md
  - 1.1.0: api/1.1.0.md
  - 1.0.7: api/1.0.7.md
  - 1.0.6: api/1.0.6.md
  - 1.0.5: api/1.0.5.md
  - 1.0.4: api/1.0.4.md
  - 1.0.3: api/1.0.3.md
  - 1.0.2: api/1.0.2.md
  - 1.0.1: api/1.0.1.md
  - 1.0.0: api/1.0.0.md
  - latest: api/latest.md
- License: license.md
